name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'
        
    - name: Restore Server
      run: dotnet restore Server/EncryptItVC.Server.csproj
      
    - name: Build Server
      run: dotnet build Server/EncryptItVC.Server.csproj --configuration Release
      
    - name: Restore Client  
      run: dotnet restore Client/EncryptItVC.Client.csproj
      
    - name: Build Client
      run: dotnet build Client/EncryptItVC.Client.csproj --configuration Release
